# Use the Node.js 22
FROM node:22

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json into the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . .

EXPOSE 3000

CMD ["npm", "run", "check"]