openapi: 3.0.1
info:
  title: User Authentication API
  description: API for user registration and login with provider-specific options.
  version: 1.0.0

servers:
  - url: http://localhost:3000/v1

paths:
  /register:
    post:
      summary: Register a new user
      description: Registers a new user to the system with a specified provider.
      responses:
        "200":
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  userId:
                    type: string
        "400":
          description: Invalid provider value
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /login:
    post:
      summary: Log in a user
      description: Logs in an existing user with a specified provider.
      parameters:
        - name: provider
          in: query
          required: true
          description: The cloud provider to use for login.
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
              examples:
                value:
                  message: "User successfully logged in"
        "401":
          description: Unauthorized, invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
